name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
    - uses: actions/checkout@v4

    - name: Make terraform.sh executable
      run: chmod +x .github/scripts/terraform.sh

    - name: Provision using Terraform
      run: |
        .github/scripts/terraform.sh init
        .github/scripts/terraform.sh "apply -auto-approve"
    
    - name: Zip frontend code and upload to S3
      working-directory: frontend
      run: |
          zip -j deploy.zip index.html authentication.js
          aws s3 cp deploy.zip s3://read-for-me-frontend/deploy.zip
    
    - name: Deploy frontend
      run: |
        aws amplify start-deployment \
            --app-id d1trqyve4ac16v \
            --branch-name dev \
            --source-url s3://read-for-me-frontend/deploy.zip \
            --source-url-type ZIP

